### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by rumkin** [Alex5646/cookie.js#1]
I've copied content of cookie.min.js into browser's console and get ReferenceError:

```
Uncaught ReferenceError: exports is not defined
```

**Comment by Alex5646** [comment]
It is necessary to support CommonJS/Node. I add a review.
https://github.com/Alex5646/cookie.js/blob/master/cookie.js#L191
I think need to add a check for existence.

Do you speak Russian? My English is bad.

**Comment by rumkin** [comment]
Good enough to discuss.
For Russian let's use skype: rumkins or better to use gitter!

**Comment by Alex5646** [comment]
Check again. Errors no longer exists.

https://github.com/Alex5646/cookie.js/blob/master/cookie.js#L191

**Comment by rumkin** [comment]
:+1: It works

**Comment by Alex5646** [comment]
Thank you.
